In [ ]:
#1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için
#dimension'ını kontrol edin


In [1]:
import numpy as np
import random

In [4]:
arr3d=np.array([[[1,2,3],[23,45,67]],[[4,5,6],[45,67,89]]])
arr3d


array([[[ 1,  2,  3],
        [23, 45, 67]],

       [[ 4,  5,  6],
        [45, 67, 89]]])

In [5]:
arr3d.ndim

3

In [ ]:
#2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.


In [6]:
np.arange(34,113,6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [ ]:
#3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)


In [7]:
np.linspace(50,500,91, dtype=int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [ ]:
#4) 100 ile 10000 arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.


In [8]:
np.logspace(2,5,8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [ ]:
#5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.


In [17]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)


In [22]:
np.zeros((6,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
#7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)


In [28]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)


In [26]:
np.eye(8,8,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
#9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün 
#değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)


In [29]:
np.eye(5,5,dtype=int)*3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [ ]:
#10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.


In [30]:
np.random.rand(6)

array([0.43916401, 0.15128169, 0.25858172, 0.98196855, 0.09495335,
       0.24770098])

In [ ]:
#11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) 
#shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.


In [34]:
x=np.random.randint(50,101,10).reshape(5,2)
x

array([[73, 79],
       [92, 85],
       [80, 91],
       [50, 61],
       [62, 64]])

In [33]:
x.shape

(5, 2)

In [ ]:
#12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan 
#(2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.


In [37]:
ar=np.random.randint(100,1000,(2,5,5))
ar

array([[[962, 268, 330, 196, 602],
        [974, 215, 475, 170, 264],
        [800, 740, 758, 766, 345],
        [414, 332, 251, 810, 634],
        [246, 526, 780, 726, 780]],

       [[193, 904, 744, 113, 317],
        [279, 938, 325, 498, 648],
        [811, 439, 413, 154, 468],
        [254, 517, 764, 490, 838],
        [592, 378, 231, 215, 958]]])

In [38]:
ar.ndim

3

In [39]:
ar.shape

(2, 5, 5)

In [ ]:
#13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. 
#Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.


In [43]:
arr2=np.random.randint(0,101,10)
arr2

array([59, 60, 93, 66, 95, 59, 76, 10, 41, 80])

In [47]:
(print(arr2.max()))
(print(arr2.min()))
(print(arr2.argmax()))
(print(arr2.argmin()))

95
10
4
7


In [ ]:
#14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 
#boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve 
#indexleme yaparak çekmeye çalışın.


In [49]:
arr3=np.random.randint(300,501,(2,2,5))
arr3

array([[[362, 481, 421, 388, 447],
        [421, 387, 394, 430, 407]],

       [[494, 456, 308, 338, 391],
        [353, 395, 319, 479, 427]]])

In [51]:
arr3[1][0][0] #or arr3[1,0,0]

494

In [54]:
arr3[1,0,2]  #or arr3[1][0][2]

308

In [ ]:
#15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e
#eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [58]:
arr_broad=np.arange(51)
arr_broad[20:36]=500
arr_broad

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])